### ISSUE TITLE
missing implementations to serialize models

### ISSUE THREAD

**Issue by proohit** [smartcorelib/smartcore#104]
I'm trying to serialize a simple `LinearRegression<f64, DenseMatrix<f64>>` model, which fails in current development state,
```
the trait `serde::ser::Serialize` is not implemented for `smartcore::linear::linear_regression::LinearRegression<f64, smartcore::linalg::naive::dense_matrix::DenseMatrix<f64>>
```
This also applies to `f32` and occurs for serializing and deserializing. It works on public version 0.2.0.

```rust
let model_binary = bincode::serialize(&model).expect("Can not serialize the model");
...
```
```rust
...
bincode::deserialize(&buf).expect("Can not deserialize the model");
...
```
## info
```toml
[dependencies]
wasm-bindgen = "=0.2.63"
smartcore = {git = "https://github.com/smartcorelib/smartcore", branch="development"}
serde = "1.0.125"
bincode = "1.3.3"
ssvm-wasi-helper = "=0.1.0"
```
